import os
import json
import torch
import torch.nn as nn
from torchvision.models import efficientnet_b0, EfficientNet_B0_Weights
from torchvision import transforms
from PIL import Image

# Fallback class list (alphabetically sorted — matches PyTorch ImageFolder order)
_FALLBACK_CLASSES = [
    "Apple___Apple_scab",
    "Apple___Black_rot",
    "Apple___Cedar_apple_rust",
    "Apple___healthy",
    "Blueberry___healthy",
    "Cherry_(including_sour)___Powdery_mildew",
    "Cherry_(including_sour)___healthy",
    "Corn_(maize)___Cercospora_leaf_spot Gray_leaf_spot",
    "Corn_(maize)___Common_rust_",
    "Corn_(maize)___Northern_Leaf_Blight",
    "Corn_(maize)___healthy",
    "Grape___Black_rot",
    "Grape___Esca_(Black_Measles)",
    "Grape___Leaf_blight_(Isariopsis_Leaf_Spot)",
    "Grape___healthy",
    "Orange___Haunglongbing_(Citrus_greening)",
    "Peach___Bacterial_spot",
    "Peach___healthy",
    "Pepper,_bell___Bacterial_spot",
    "Pepper,_bell___healthy",
    "Potato___Early_blight",
    "Potato___Late_blight",
    "Potato___healthy",
    "Raspberry___healthy",
    "Soybean___healthy",
    "Squash___Powdery_mildew",
    "Strawberry___Leaf_scorch",
    "Strawberry___healthy",
    "Tomato___Bacterial_spot",
    "Tomato___Early_blight",
    "Tomato___Late_blight",
    "Tomato___Leaf_Mold",
    "Tomato___Septoria_leaf_spot",
    "Tomato___Spider_mites Two-spotted_spider_mite",
    "Tomato___Target_Spot",
    "Tomato___Tomato_Yellow_Leaf_Curl_Virus",
    "Tomato___Tomato_mosaic_virus",
    "Tomato___healthy",
]

_BASE_DIR = os.path.dirname(__file__)

# Load class names from file if available (generated by training notebook)
_class_names_path = os.path.join(_BASE_DIR, "class_names.json")
if os.path.exists(_class_names_path):
    with open(_class_names_path) as f:
        CLASS_NAMES = json.load(f)
else:
    CLASS_NAMES = _FALLBACK_CLASSES

NUM_CLASSES = len(CLASS_NAMES)

# Image preprocessing — matches val_transforms used during training
_preprocess = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.485, 0.456, 0.406],
                         std=[0.229, 0.224, 0.225]),
])

_model = None


def _build_model():
    model = efficientnet_b0(weights=None)
    in_features = model.classifier[1].in_features
    model.classifier = nn.Sequential(
        nn.Dropout(p=0.4, inplace=True),
        nn.Linear(in_features, NUM_CLASSES),
    )
    return model


def load_model():
    global _model, CLASS_NAMES, NUM_CLASSES
    if _model is not None:
        return _model

    model_path = os.path.join(_BASE_DIR, "model.pt")
    if not os.path.exists(model_path):
        print("WARNING: model.pt not found — predictions will be random.")
        model = _build_model()
        model.eval()
        _model = model
        return model

    # Try 1: checkpoint dict saved by train.ipynb  →  {'model_state_dict': ..., 'class_names': ...}
    # Try 2: raw state_dict                         →  torch.save(model.state_dict(), path)
    # Try 3: full model object                      →  torch.save(model, path)
    # Try 4: TorchScript                            →  torch.jit.save(scripted_model, path)
    model = None

    try:
        checkpoint = torch.load(model_path, map_location="cpu", weights_only=False)

        if isinstance(checkpoint, dict) and "model_state_dict" in checkpoint:
            # Case 1: our train.ipynb checkpoint
            state_dict = checkpoint["model_state_dict"]
            if "class_names" in checkpoint:
                CLASS_NAMES = checkpoint["class_names"]
                NUM_CLASSES = len(CLASS_NAMES)
            model = _build_model()
            model.load_state_dict(state_dict)
            print(f"Loaded checkpoint dict ({NUM_CLASSES} classes)")

        elif isinstance(checkpoint, dict):
            # Case 2: raw state_dict
            model = _build_model()
            model.load_state_dict(checkpoint)
            print(f"Loaded raw state_dict ({NUM_CLASSES} classes)")

        else:
            # Case 3: full model object (torch.save(model, path))
            model = checkpoint
            print("Loaded full model object")

    except Exception as e:
        print(f"torch.load failed ({e}), trying torch.jit.load...")
        try:
            # Case 4: TorchScript
            model = torch.jit.load(model_path, map_location="cpu")
            print(f"Loaded TorchScript model ({NUM_CLASSES} classes)")
        except Exception as e2:
            raise RuntimeError(
                f"Could not load model.pt.\n"
                f"torch.load error:     {e}\n"
                f"torch.jit.load error: {e2}\n"
                f"Re-train and re-download model.pt from Kaggle."
            )

    model.eval()
    _model = model
    return model


def predict(image: Image.Image, top_k: int = 3) -> list[dict]:
    """Run inference on a PIL image. Returns top_k predictions sorted by confidence."""
    model = load_model()

    if image.mode != "RGB":
        image = image.convert("RGB")

    tensor = _preprocess(image).unsqueeze(0)  # [1, 3, 224, 224]

    with torch.no_grad():
        logits = model(tensor)
        probs = torch.softmax(logits, dim=1)[0]
        top_probs, top_indices = probs.topk(min(top_k, NUM_CLASSES))

    return [
        {
            "class_name": CLASS_NAMES[idx.item()],
            "confidence": round(prob.item() * 100, 2),
            "index": idx.item(),
        }
        for prob, idx in zip(top_probs, top_indices)
    ]
